apiVersion: apps/v1
kind: Deployment
metadata:
  name: gitops-app-deployment
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gitops-app
  template:
    metadata:
      labels:
        app: gitops-app
    spec:
      containers:
      - name: web-app
        image: acrigitopsprojectunique123.azurecr.io/gitops-app:cb3ab2197ea3c2f76f15d6b7d70cb0c6e443ef4ae7a0a243131b29483236c5bd # Will be dynamically updated by CI
        ports:
        - containerPort: 3000